### PR TITLE
Retrieve udev rules path through pkg-config if possible

### PR DESCRIPTION
**Pull request by twolife**
let's reduce the delta between here and the Debian package

### CODE REVIEW

**Comment by davidebeatrici** [comment]
@RalfJung Please let me know whether anything else is needed for the Debian package, before I release 1.3.3/1.4.0.

**Comment by RalfJung** [comment]
I've mostly handed off maintenance of the package, and it's been years since I did any significant work on it, so unfortunately I lost most context. You can see https://salsa.debian.org/debian/osspd/-/tree/master/debian/patches?ref_type=heads for the patches we have in Debian on top of version 1.3.2.

**Comment by davidebeatrici** [comment]
No problem. I just realized @twolife is listed as a maintainer for the package...

**Comment by twolife** [comment]
@davidebeatrici most of the patches have already been merged here (one notable exception is a patch I found in the archlinux package https://salsa.debian.org/debian/osspd/-/blob/master/debian/patches/Log-the-right-slave-program-name.patch ).

If we could get a proper new release here it would be really nice, so that i could clean up the place in Debian :smiley:

**Comment by davidebeatrici** [comment]
Oh, I was wondering where that patch came from because it's dated 2020-12-18 but wasn't in the Debian package when I merged all patches here in 2022.

Added through #16 and created a new release, thanks!

**Pull request merged**
