### PR TITLE
Fix compilation with -Werror=format-security

### PR DESCRIPTION
**Pull request by davidebeatrici**
@RalfJung Looks like your commit got lost: 097dc7b6b16cd277b7bd3a9674eb13b3865a3eb1

### CODE REVIEW

**Comment by RalfJung** [comment]
IIRC I submitted this to a mailing list or so, but upstream has been dead for years so I don't think the patch ever got applied.

EDIT: Ah hm no [this file](https://salsa.debian.org/debian/osspd/-/blob/master/debian/patches/0001-Fix-compilation-with-Werror-format-security.patch) says it got "Committed upstream". And according to my local clone it was indeed in `git://git.code.sf.net/p/osspd/code` at some point.

**Comment by RalfJung** [comment]
This seems to not be the only lost commit; 3a9a0196b531f011983160f1db146b870b260c4d also was in `git://git.code.sf.net/p/osspd/code` but does not seem to be in this repo.

**Comment by davidebeatrici** [comment]
Oh, it's probably as I suspected: this was not the master repository at one point and the last commits were not mirrored.

**Comment by RalfJung** [comment]
So which is the master repo these days? I have two remotes in my checkout:
- git://git.code.sf.net/p/osspd/code
- git://fuse.git.sourceforge.net/gitroot/fuse/osspd

https://sourceforge.net/projects/osspd/ contains no indication that it is outdated. (That's what I set as the 'homepage' when I created the Debian package.)

If this repo is official now, then I don't think there is a way that one could know this. Is there a better 'homepage' I could set?

**Comment by davidebeatrici** [comment]
From https://sourceforge.net/projects/fuse:



`git://fuse.git.sourceforge.net/gitroot/fuse/osspd` does not seem to be accessible anymore:

> fatal: remote error: access denied or repository not exported: /gitroot/fuse/osspd

I assume the master repo is this one and they simply forgot to update the page on SourceForge.

**Comment by RalfJung** [comment]
Btw, here is the [link proving that this was indeed committed upstream](https://sourceforge.net/p/osspd/code/ci/097dc7b6b16cd277b7bd3a9674eb13b3865a3eb1).

**Comment by davidebeatrici** [comment]
Yeah, the repos seem to have diverged right after 4c6161d951daa98f6463904f76b3fa2ce7216194.

**Comment by davidebeatrici** [comment]
SourceForge discussion continues in #6.

**Pull request merged**
