### PR TITLE
Replace Makefile with CMake project

### PR DESCRIPTION
**Pull request by davidebeatrici**
@RalfJung Please let me know if you like it and/or have any suggestions.

### CODE REVIEW

**Comment by RalfJung** [comment]
Sorry, I don't have the time to help with upstream maintenance here.

**Comment by davidebeatrici** [comment]
You're the Debian package maintainer, I would like to know whether the project works for you (i.e. doesn't make your job harder).

**Comment by RalfJung** [comment]
I mean, it'll be quite a bit of work to adjust the build system. I don't know if/when I will have time to do that -- being maintainer for a package with dead upstream was pretty convenient. ;)  I don't use osspd myself any more, so I am unlikely to spend much time on it. It is also the only Debian package I maintain, so every two years when I get back to it I have to re-learn the Debian packaging workflow...

But I am not sure if that should affect your decision. Worst case, the package needs a new Debian maintainer, and until we find one we just keep it as-is. It was basically unchanged for a decade, after all, so it's not like "nothing happens" would be a new situation for osspd in Debian.

Simon McVittie `<smcv@debian.org>` has [offered](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990121) for the Debian Games Team to absorb the package, and we already moved it to a git repo on shared infrastructure, so hopefully finding a new maintainer, if needed, shouldn't be too hard.

**Comment by RalfJung** [comment]
Ah, turns out they are on Github, so Cc @smcv

**Comment by davidebeatrici** [comment]
Oh, I see, I thought you were still the active maintainer.

Let's wait for @smcv then, to at least ensure that the CMake project provides enough flexibility.

**Pull request merged**
